version: '3.8'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE=django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE=fastapi
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn API.main:app --host 0.0.0.0 --port 8001
